# Generated by Django 3.0.5 on 2020-05-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honestomiguel', '0002_auto_20200503_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
